# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OxOpLoyzHtWUB31IGrwN43ZcGfx4l1_
"""

import os
import textwrap
import streamlit as st
from streamlit.components.v1 import html as components_html

# -----------------------------
# Config & Theming
# -----------------------------
st.set_page_config(
    page_title="SDG9 Assistant · Chatbot",
    page_icon="💬",
    layout="wide",
)

# You can hardcode your Agent ID or read from secrets/env
DEFAULT_AGENT_ID = "371cfe48-d365-4014-8a1a-d60b773b460a"
AGENT_ID = st.secrets.get("DIALOGFLOW_AGENT_ID", os.getenv("DIALOGFLOW_AGENT_ID", DEFAULT_AGENT_ID))

CHAT_TITLE = "SDG9_Assistant"
LANG_CODE = "en"
WELCOME_INTENT = "WELCOME"

# -----------------------------
# Reusable Renderers
# -----------------------------
def render_header():
    st.markdown("""
    <div class="hero">
      <div class="hero-badge">SDG 9</div>
      <h1>Build resilient infrastructure, promote inclusive &amp; sustainable industrialization, and foster innovation</h1>
      <p class="subhead">
        Talk to the SDG9 Assistant for quick explanations, examples, assessments, funding guidance, and standards.
      </p>
    </div>
    """, unsafe_allow_html=True)

def render_feature_tiles():
    st.markdown("""
    <div class="grid">
      <div class="tile">
        <h3>Explain SDG 9</h3>
        <p>Get a crisp overview of resilient infrastructure, sustainable industrialization, and innovation.</p>
      </div>
      <div class="tile">
        <h3>Examples &amp; Use-cases</h3>
        <p>See practical, sector-friendly actions: energy efficiency, resource recovery, digitalization.</p>
      </div>
      <div class="tile">
        <h3>Readiness Assessment</h3>
        <p>Provide sector, region, plant size, budget &amp; priority to get a tailored quick plan.</p>
      </div>
      <div class="tile">
        <h3>Funding &amp; Standards</h3>
        <p>Explore typical funding avenues and management system standards to guide implementation.</p>
      </div>
    </div>
    """, unsafe_allow_html=True)

def render_sidebar():
    with st.sidebar:
        st.markdown("### 🔧 Settings")
        st.write("You can keep these as default.")
        st.text_input("Agent ID", value=AGENT_ID, help="Dialogflow ES Agent ID")
        st.text_input("Chat title", value=CHAT_TITLE)
        st.text_input("Language code", value=LANG_CODE)
        st.text_input("Initial intent", value=WELCOME_INTENT)
        st.markdown("---")
        st.markdown("#### Quick Tips")
        st.markdown("""
        - Start with **“What is SDG 9?”**
        - Try **“Assess my factory”**
        - Ask **“Funding”** or **“Standards”**
        """)

def render_messenger_widget(agent_id: str, chat_title: str, lang: str, initial_intent: str):
    """
    Embeds Dialogflow Messenger in Streamlit via a small HTML island.
    Also applies aesthetic colors and positions the widget expanded on desktop.
    """
    widget_html = f"""
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger
      intent="{initial_intent}"
      chat-title="{chat_title}"
      agent-id="{agent_id}"
      language-code="{lang}"
      chat-icon=""
    ></df-messenger>

    <style>
      /* Page baseline */
      :root {{
        --bg: #0b1220;
        --card: #0f172a;
        --muted: #b6c2ff;
        --text: #e6ebff;
        --accent: #7c9cff;
        --accent-2: #99f6e4;
      }}
      body, .main, .block-container {{
        background: var(--bg) !important;
      }}

      /* Hero */
      .hero {{
        padding: 32px 0 8px;
        background: linear-gradient(135deg, rgba(124,156,255,0.18), rgba(153,246,228,0.12));
        border-radius: 20px;
        border: 1px solid rgba(124,156,255,0.25);
        box-shadow: 0 10px 30px rgba(0,0,0,0.35);
        padding-left: 24px; padding-right: 24px;
      }}
      .hero-badge {{
        display:inline-block; padding:6px 12px; font-weight:600; font-size:12px;
        color:#0b1220; background: var(--accent-2); border-radius:999px; margin-bottom:10px;
      }}
      .hero h1 {{
        margin: 0 0 6px 0; color: var(--text); line-height:1.2; font-size: 28px;
      }}
      .subhead {{ color: var(--muted); margin-top: 4px; }}

      /* Tiles */
      .grid {{
        margin-top: 22px;
        display: grid; gap: 14px;
        grid-template-columns: repeat(4, minmax(0, 1fr));
      }}
      @media (max-width: 1200px) {{
        .grid {{ grid-template-columns: repeat(2, 1fr); }}
      }}
      @media (max-width: 700px) {{
        .grid {{ grid-template-columns: 1fr; }}
      }}
      .tile {{
        background: var(--card); border: 1px solid rgba(124,156,255,0.2);
        border-radius: 16px; padding: 16px;
      }}
      .tile h3 {{ color: var(--text); margin-top: 0; }}
      .tile p {{ color: var(--muted); }}

      /* Dialogflow Messenger theming */
      df-messenger {{
        --df-messenger-bot-message: #0f172a;
        --df-messenger-button-titlebar-color: #7c9cff;
        --df-messenger-button-titlebar-font-color: #0b1220;
        --df-messenger-chat-background-color: #0b1220;
        --df-messenger-font-color: #e6ebff;
        --df-messenger-send-icon: #7c9cff;
        --df-messenger-user-message: #1d2a44;
        z-index: 9999;
      }}
      df-messenger .df-titlebar-title {{
        font-weight: 700 !important;
      }}

      /* Keep the chat open on larger screens for demo feel */
      @media (min-width: 1024px) {{
        df-messenger {{ position: fixed; right: 24px; bottom: 24px; }}
      }}
    </style>
    """

    components_html(widget_html, height=120, scrolling=False)

def render_footer():
    st.markdown("""
    <div class="footer">
      <p>Need ideas? Try <code>What is SDG 9?</code>, <code>Assess my factory</code>, or <code>Funding</code>.</p>
    </div>
    """, unsafe_allow_html=True)


# -----------------------------
# Page
# -----------------------------
render_sidebar()
render_header()
render_feature_tiles()
render_messenger_widget(AGENT_ID, CHAT_TITLE, LANG_CODE, WELCOME_INTENT)
render_footer()